name: flutter_ty_app
version: 1.6.1+1
publish_to: none
description: tyapp
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  get: 4.6.6
  get_storage: ^2.0.3
  # 网络相关
  dio: ^5.3.0
  retrofit: '>=4.0.0 <5.0.0'
  # 屏幕适配
  flutter_screenutil: ^5.9.0
  # 工具类
  common_utils: ^2.0.1
  # 下拉刷新
  pull_to_refresh: ^2.0.0
  cached_network_image:
  flutter_svg: ^2.0.7
  encrypt: ^5.0.3
  scrollview_observer: ^1.16.5
  scroll_to_index: ^3.0.1
  marquee: ^2.2.3
  web_socket_channel: ^2.4.5
  #toast
  oktoast: ^3.3.2+1
  flutter_inappwebview: ^6.0.0

  # 文本适配
  auto_size_text: ^3.0.0

  # 显示HTMl控件
  flutter_widget_from_html: ^0.10.3
  #弹框
  flutter_popup:
  super_tooltip:

  # 多语言
  flutter_localizations:
    sdk: flutter
    # 布局工具
  sliver_tools:
  #版本信息

  video_player:
  # fijkplayer: ^0.11.0
  fijkplayer:
    path: packages/fijkplayer-0.11.0
  # flutter_vlc_player: ^7.4.1
  flutter_vlc_player: ^7.4.1

  visibility_detector: ^0.4.0+2

  # 列表滚动
  extended_nested_scroll_view: ^6.2.1

  # 骨架屏
  shimmer: ^3.0.0
  #锁
  mutex: ^3.1.0
  device_info_plus: ^10.1.0
  gif: ^2.3.0

  #检测全局网络状态
  connectivity_plus: ^4.0.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - res/oss/
    - fonts/
#  fonts:
#    - family: Akrobat
#      fonts:
#        - asset: fonts/Akrobat-Bold.otf
