// This file is created by egg-ts-helper@1.35.1
// Do not modify this file!!!!!!!!!
/* eslint-disable */

import 'egg';
import ExportAdmin = require('../../../app/model/admin');
import ExportAdminRecord = require('../../../app/model/adminRecord');
import ExportAnimBaseData = require('../../../app/model/animBaseData');
import ExportAnimTeamData = require('../../../app/model/animTeamData');
import ExportAnimTemplate = require('../../../app/model/animTemplate');
import ExportAppAssets = require('../../../app/model/appAssets');
import ExportAppLogger = require('../../../app/model/appLogger');
import ExportAppSdkVersion = require('../../../app/model/appSdkVersion');
import ExportArticle = require('../../../app/model/article');
import ExportAssetsKey = require('../../../app/model/assetsKey');
import ExportBSdkDocpool = require('../../../app/model/b_sdk_docpool');
import ExportBSdkMddocpool = require('../../../app/model/b_sdk_mddocpool');
import ExportBSdkMenu = require('../../../app/model/b_sdk_menu');
import ExportClientLanguage = require('../../../app/model/clientLanguage');
import ExportClientMenu = require('../../../app/model/clientMenu');
import ExportClientRole = require('../../../app/model/clientRole');
import ExportCodeTag = require('../../../app/model/codeTag');
import ExportCompetition = require('../../../app/model/competition');
import ExportCompetitionSliceSchema = require('../../../app/model/competition_slice_schema');
import ExportComponentDoc = require('../../../app/model/componentDoc');
import ExportComponentKey = require('../../../app/model/componentKey');
import ExportConfigVersion = require('../../../app/model/configVersion');
import ExportCssKey = require('../../../app/model/cssKey');
import ExportDocpool = require('../../../app/model/docpool');
import ExportFaq = require('../../../app/model/faq');
import ExportFileUploadLog = require('../../../app/model/fileUploadLog');
import ExportI18nKey = require('../../../app/model/i18nKey');
import ExportImgDescription = require('../../../app/model/imgDescription');
import ExportJsKey = require('../../../app/model/jsKey');
import ExportKeyChangeRecord = require('../../../app/model/keyChangeRecord');
import ExportKeyConfigRecord = require('../../../app/model/keyConfigRecord');
import ExportKeyGroup = require('../../../app/model/keyGroup');
import ExportLanguage = require('../../../app/model/language');
import ExportLayoutTemplate = require('../../../app/model/layoutTemplate');
import ExportMdHistory = require('../../../app/model/mdHistory');
import ExportMddocpool = require('../../../app/model/mddocpool');
import ExportMenu = require('../../../app/model/menu');
import ExportMiddlewareInterface = require('../../../app/model/middlewareInterface');
import ExportModularSettingCache = require('../../../app/model/modularSettingCache');
import ExportPackingConfig = require('../../../app/model/packingConfig');
import ExportPackingProcess = require('../../../app/model/packingProcess');
import ExportPackingRecord = require('../../../app/model/packingRecord');
import ExportQuestionTopic = require('../../../app/model/questionTopic');
import ExportRole = require('../../../app/model/role');
import ExportScanMatch = require('../../../app/model/scanMatch');
import ExportThemeTemplate = require('../../../app/model/themeTemplate');
import ExportUpdateRecord = require('../../../app/model/updateRecord');
import ExportUser = require('../../../app/model/user');
import ExportVersionGroup = require('../../../app/model/versionGroup');
import ExportMatchMaterialAthleteManage = require('../../../app/model/matchMaterial/athleteManage');
import ExportMatchMaterialHistoricalVideos = require('../../../app/model/matchMaterial/historical_videos');
import ExportMatchMaterialMatchOyh = require('../../../app/model/matchMaterial/match_oyh');
import ExportMatchMaterialMatchOzb = require('../../../app/model/matchMaterial/match_ozb');
import ExportMatchMaterialVenueManage = require('../../../app/model/matchMaterial/venueManage');

declare module 'egg' {
  interface IModel {
    Admin: ReturnType<typeof ExportAdmin>;
    AdminRecord: ReturnType<typeof ExportAdminRecord>;
    AnimBaseData: ReturnType<typeof ExportAnimBaseData>;
    AnimTeamData: ReturnType<typeof ExportAnimTeamData>;
    AnimTemplate: ReturnType<typeof ExportAnimTemplate>;
    AppAssets: ReturnType<typeof ExportAppAssets>;
    AppLogger: ReturnType<typeof ExportAppLogger>;
    AppSdkVersion: ReturnType<typeof ExportAppSdkVersion>;
    Article: ReturnType<typeof ExportArticle>;
    AssetsKey: ReturnType<typeof ExportAssetsKey>;
    BSdkDocpool: ReturnType<typeof ExportBSdkDocpool>;
    BSdkMddocpool: ReturnType<typeof ExportBSdkMddocpool>;
    BSdkMenu: ReturnType<typeof ExportBSdkMenu>;
    ClientLanguage: ReturnType<typeof ExportClientLanguage>;
    ClientMenu: ReturnType<typeof ExportClientMenu>;
    ClientRole: ReturnType<typeof ExportClientRole>;
    CodeTag: ReturnType<typeof ExportCodeTag>;
    Competition: ReturnType<typeof ExportCompetition>;
    CompetitionSliceSchema: ReturnType<typeof ExportCompetitionSliceSchema>;
    ComponentDoc: ReturnType<typeof ExportComponentDoc>;
    ComponentKey: ReturnType<typeof ExportComponentKey>;
    ConfigVersion: ReturnType<typeof ExportConfigVersion>;
    CssKey: ReturnType<typeof ExportCssKey>;
    Docpool: ReturnType<typeof ExportDocpool>;
    Faq: ReturnType<typeof ExportFaq>;
    FileUploadLog: ReturnType<typeof ExportFileUploadLog>;
    I18nKey: ReturnType<typeof ExportI18nKey>;
    ImgDescription: ReturnType<typeof ExportImgDescription>;
    JsKey: ReturnType<typeof ExportJsKey>;
    KeyChangeRecord: ReturnType<typeof ExportKeyChangeRecord>;
    KeyConfigRecord: ReturnType<typeof ExportKeyConfigRecord>;
    KeyGroup: ReturnType<typeof ExportKeyGroup>;
    Language: ReturnType<typeof ExportLanguage>;
    LayoutTemplate: ReturnType<typeof ExportLayoutTemplate>;
    MdHistory: ReturnType<typeof ExportMdHistory>;
    Mddocpool: ReturnType<typeof ExportMddocpool>;
    Menu: ReturnType<typeof ExportMenu>;
    MiddlewareInterface: ReturnType<typeof ExportMiddlewareInterface>;
    ModularSettingCache: ReturnType<typeof ExportModularSettingCache>;
    PackingConfig: ReturnType<typeof ExportPackingConfig>;
    PackingProcess: ReturnType<typeof ExportPackingProcess>;
    PackingRecord: ReturnType<typeof ExportPackingRecord>;
    QuestionTopic: ReturnType<typeof ExportQuestionTopic>;
    Role: ReturnType<typeof ExportRole>;
    ScanMatch: ReturnType<typeof ExportScanMatch>;
    ThemeTemplate: ReturnType<typeof ExportThemeTemplate>;
    UpdateRecord: ReturnType<typeof ExportUpdateRecord>;
    User: ReturnType<typeof ExportUser>;
    VersionGroup: ReturnType<typeof ExportVersionGroup>;
    MatchMaterial: {
      AthleteManage: ReturnType<typeof ExportMatchMaterialAthleteManage>;
      HistoricalVideos: ReturnType<typeof ExportMatchMaterialHistoricalVideos>;
      MatchOyh: ReturnType<typeof ExportMatchMaterialMatchOyh>;
      MatchOzb: ReturnType<typeof ExportMatchMaterialMatchOzb>;
      VenueManage: ReturnType<typeof ExportMatchMaterialVenueManage>;
    }
  }
}
